"""Generate and update .kimi/PROJECT.md with structured observations."""

from __future__ import annotations

import threading
import time
from pathlib import Path
from typing import Any

from loguru import logger

from mneme.db.structured_store import StructuredObservationStore


class ProjectMdGenerator:
    """Generate PROJECT.md from structured observations.

    Debounced writes: updates are batched and written every 30 seconds.
    Max entries: 50. Cleanup: entries older than 30 days are removed.
    """

    DEBOUNCE_SECONDS = 30
    MAX_ENTRIES = 50
    MAX_AGE_DAYS = 30

    def __init__(self) -> None:
        self.store = StructuredObservationStore()
        self._pending: set[str] = set()  # project names pending update
        self._timer: threading.Timer | None = None
        self._lock = threading.Lock()

    def schedule_update(self, project: str) -> None:
        """Schedule a PROJECT.md update for a project (debounced)."""
        with self._lock:
            self._pending.add(project)
            if self._timer:
                self._timer.cancel()
            self._timer = threading.Timer(self.DEBOUNCE_SECONDS, self._flush)
            self._timer.daemon = True
            self._timer.start()

    def _flush(self) -> None:
        """Write all pending PROJECT.md files."""
        with self._lock:
            projects = list(self._pending)
            self._pending.clear()
            self._timer = None

        for project in projects:
            try:
                self._write_project_md(project)
            except Exception as e:
                logger.error(f"Failed to write PROJECT.md for {project}: {e}")

    def _write_project_md(self, project: str) -> None:
        """Write PROJECT.md and AGENTS.md for a single project.

        AGENTS.md is the kimi-cli native format (B.8).
        PROJECT.md is kept for backward compatibility.
        """
        # Find project directory from sessions
        project_dir = self._find_project_dir(project)
        if not project_dir:
            logger.debug(f"Project directory not found for {project}")
            return

        kimi_dir = Path(project_dir) / ".kimi"
        kimi_dir.mkdir(parents=True, exist_ok=True)

        # Get recent structured observations
        observations = self.store.get_for_injection(project=project, limit=self.MAX_ENTRIES)

        if not observations:
            return

        # Write AGENTS.md (kimi-cli native format)
        agents_md_path = kimi_dir / "AGENTS.md"
        agents_lines = self._format_agents_md(project, observations)
        agents_md_path.write_text("\n".join(agents_lines), encoding="utf-8")

        # Also write PROJECT.md for backward compatibility
        project_md_path = kimi_dir / "PROJECT.md"
        project_lines = self._format_project_md(project, observations)
        project_md_path.write_text("\n".join(project_lines), encoding="utf-8")

        logger.info(f"AGENTS.md + PROJECT.md updated for {project}: {len(observations)} entries")

    def _find_project_dir(self, project: str) -> str | None:
        """Find project directory from sessions table."""
        with self.store._get_conn() as conn:
            row = conn.execute(
                "SELECT cwd FROM sessions WHERE project = ? OR cwd LIKE ? ORDER BY started_at DESC LIMIT 1",
                (project, f"%{project}%"),
            ).fetchone()
        return row["cwd"] if row else None

    def _format_agents_md(self, project: str, observations: list[dict[str, Any]]) -> list[str]:
        """Format observations as AGENTS.md (kimi-cli native format).

        AGENTS.md is read by kimi-cli for context. It uses a simpler,
        more direct format than PROJECT.md.
        """
        lines = [
            f"# {project}",
            "",
            "## Context",
            "",
            "This file is auto-generated by kimi-mneme from structured observations.",
            "It contains key facts, decisions, and discoveries from past sessions.",
            "",
            "## Key Facts",
            "",
        ]

        # Collect unique facts
        seen_facts: set[str] = set()
        for obs in observations:
            for fact in obs.get("facts", [])[:2]:
                if fact and fact not in seen_facts:
                    seen_facts.add(fact)
                    lines.append(f"- {fact}")

        if not seen_facts:
            lines.append("_No key facts recorded yet._")

        lines.extend([
            "",
            "## Recent Activity",
            "",
        ])

        type_emoji = {
            "bugfix": "🐛",
            "feature": "✨",
            "refactor": "♻️",
            "change": "📝",
            "discovery": "🔍",
            "decision": "🎯",
        }

        for obs in observations[:20]:
            obs_type = obs.get("type", "discovery")
            emoji = type_emoji.get(obs_type, "•")
            title = obs.get("title", "Untitled")
            narrative = obs.get("narrative", "")

            lines.append(f"### {emoji} {title}")
            if narrative:
                narrative = " ".join(narrative.split())
                narrative = narrative[:150] + "..." if len(narrative) > 150 else narrative
                lines.append(narrative)

            files = (obs.get("files_modified", []) + obs.get("files_read", []))[:3]
            if files:
                lines.append(f"**Files:** {', '.join(files)}")
            lines.append("")

        lines.extend([
            "---",
            "",
            f"*Auto-generated by kimi-mneme v2.0.0 | {len(observations)} observations*",
        ])

        return lines

    def _format_project_md(self, project: str, observations: list[dict[str, Any]]) -> list[str]:
        """Format observations as PROJECT.md (legacy format, kept for compatibility)."""
        lines = [
            f"# Project Context: {project}",
            "",
            "## Recent Activity",
            "",
            "| Time | Type | Title | Files |",
            "|------|------|-------|-------|",
        ]

        type_emoji = {
            "bugfix": "🐛",
            "feature": "✨",
            "refactor": "♻️",
            "change": "📝",
            "discovery": "🔍",
            "decision": "🎯",
        }

        for obs in observations:
            created = obs.get("created_at", "")[:16] if obs.get("created_at") else ""
            obs_type = obs.get("type", "discovery")
            emoji = type_emoji.get(obs_type, "•")
            title = obs.get("title", "Untitled")

            files = (obs.get("files_modified", []) + obs.get("files_read", []))[:3]
            files_str = ", ".join(files) if files else "—"

            lines.append(f"| {created} | {emoji} {obs_type} | {title} | {files_str} |")

        lines.extend([
            "",
            "## Key Facts",
            "",
        ])

        seen_facts: set[str] = set()
        for obs in observations:
            for fact in obs.get("facts", [])[:2]:
                if fact and fact not in seen_facts:
                    seen_facts.add(fact)
                    lines.append(f"- {fact}")

        lines.extend([
            "",
            "---",
            "",
            f"*Generated by kimi-mneme | {len(observations)} observations*",
        ])

        return lines


# Global singleton
_project_md_generator: ProjectMdGenerator | None = None
_project_md_lock = threading.Lock()


def get_project_md_generator() -> ProjectMdGenerator:
    """Get or create the global PROJECT.md generator."""
    global _project_md_generator
    with _project_md_lock:
        if _project_md_generator is None:
            _project_md_generator = ProjectMdGenerator()
        return _project_md_generator
